---
- name: restart minecraft
  service:
    name: minecraft
    state: restarted

- name: stop minecraft
  service:
    name: minecraft
    state: stopped

- name: start minecraft
  service:
    name: minecraft
    state: started
